### ISSUE TITLE
SyncAdapter crash

### ISSUE THREAD

**Issue by adamwolf** [beeminder/beedroid-issues#57]
A few users are showing:

W/SyncAdapter(22601): at com.beeminder.beeminder.client.NetworkUtilities.fetchGoals(NetworkUtilities.java:1666)
W/SyncAdapter(22601): at com.beeminder.beeminder.client.NetworkUtilities.tryFetchGoals(NetworkUtilities.java:1704)
W/SyncAdapter(22601): at com.beeminder.beeminder.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:228)
W/SyncAdapter(22601): at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)

We need to turn up logging on this section in production so we can see what's going on.  I cannot reproduce the issue, but unfortunately a few users can, consistently.

**Comment by adamwolf** [comment]
This may be moot if we replace SyncAdapter with WorkManager (#77)
